In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
x

tensor([[1.0561e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 1.0745e-38, 9.6429e-39],
        [1.0561e-38, 9.1837e-39, 1.0653e-38],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [9.6429e-39, 1.0745e-38, 9.2755e-39]])

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3514, 0.7148, 0.2486],
        [0.5283, 0.8048, 0.0874],
        [0.0274, 0.2474, 0.0021],
        [0.1534, 0.9330, 0.6807],
        [0.1243, 0.0210, 0.7034]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x.dtype

torch.int64

In [6]:
x = torch.zeros(5, 3).long()
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.0921, -0.7123,  0.3038],
        [ 1.5353,  0.6811,  1.2964],
        [-1.0697, -1.4200,  0.2946],
        [ 0.9051,  0.9325, -0.6143],
        [-0.7075, -0.7967, -0.9361]])

In [10]:
x.shape

torch.Size([5, 3])

In [11]:
x.size()

torch.Size([5, 3])

In [12]:
y = torch.rand(5, 3)
y

tensor([[0.6444, 0.6429, 0.5423],
        [0.8103, 0.1589, 0.1342],
        [0.6076, 0.3081, 0.7718],
        [0.5167, 0.5852, 0.7991],
        [0.6833, 0.5093, 0.8944]])

In [13]:
x + y

tensor([[ 0.5523, -0.0694,  0.8460],
        [ 2.3456,  0.8400,  1.4305],
        [-0.4620, -1.1118,  1.0664],
        [ 1.4218,  1.5177,  0.1848],
        [-0.0242, -0.2874, -0.0417]])

In [14]:
torch.add(x, y)

tensor([[ 0.5523, -0.0694,  0.8460],
        [ 2.3456,  0.8400,  1.4305],
        [-0.4620, -1.1118,  1.0664],
        [ 1.4218,  1.5177,  0.1848],
        [-0.0242, -0.2874, -0.0417]])

In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.5523, -0.0694,  0.8460],
        [ 2.3456,  0.8400,  1.4305],
        [-0.4620, -1.1118,  1.0664],
        [ 1.4218,  1.5177,  0.1848],
        [-0.0242, -0.2874, -0.0417]])

In [16]:
y.add_(x)
y

tensor([[ 0.5523, -0.0694,  0.8460],
        [ 2.3456,  0.8400,  1.4305],
        [-0.4620, -1.1118,  1.0664],
        [ 1.4218,  1.5177,  0.1848],
        [-0.0242, -0.2874, -0.0417]])

In [17]:
x[1:, 1:]

tensor([[ 0.6811,  1.2964],
        [-1.4200,  0.2946],
        [ 0.9325, -0.6143],
        [-0.7967, -0.9361]])

In [18]:
x = torch.randn(4, 4)
y = x.view(16)
y

tensor([-0.5440,  0.0475, -0.8571, -1.0271,  0.0275, -0.3031, -1.2155,  0.9060,
        -0.5216,  0.0447,  2.2364, -1.1918,  0.6663,  0.6765,  0.4681, -0.1460])

In [19]:
x = torch.randn(1)
x

tensor([-2.6335])

In [20]:
x.item()

-2.6334667205810547

In [21]:
x = torch.randn(4, 4)
print(x)
x.transpose(1, 0)

tensor([[-1.4833, -1.0354,  0.7381,  0.4910],
        [-1.7146, -1.6016,  1.3057, -1.2688],
        [ 1.3400, -0.1270,  1.6514,  0.0863],
        [ 0.3611, -1.2102,  0.1671,  1.2603]])


tensor([[-1.4833, -1.7146,  1.3400,  0.3611],
        [-1.0354, -1.6016, -0.1270, -1.2102],
        [ 0.7381,  1.3057,  1.6514,  0.1671],
        [ 0.4910, -1.2688,  0.0863,  1.2603]])

In [22]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [23]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [24]:
b[1] = 2
a

tensor([1., 2., 1., 1., 1.])

In [25]:
import numpy as np

In [26]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1 , out=a)  # 没有分配额外内存
a

array([2., 2., 2., 2., 2.])

In [27]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [28]:
a = a + 1 # 分配额外内存
a

array([3., 3., 3., 3., 3.])

In [29]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [31]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([[-0.4833, -0.0354,  1.7381,  1.4910],
        [-0.7146, -0.6016,  2.3057, -0.2688],
        [ 2.3400,  0.8730,  2.6514,  1.0863],
        [ 1.3611, -0.2102,  1.1671,  2.2603]], device='cuda:0')
tensor([[-0.4833, -0.0354,  1.7381,  1.4910],
        [-0.7146, -0.6016,  2.3057, -0.2688],
        [ 2.3400,  0.8730,  2.6514,  1.0863],
        [ 1.3611, -0.2102,  1.1671,  2.2603]], dtype=torch.float64)


In [35]:
N, D_in, H, D_out = 64, 1000, 100, 10

x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)
learning_rate = 1e-6
for it in range(500):
    h = x.dot(w1) # N * H
    h_relu = np.maximum(h, 0) # N * H
    y_pred = h_relu.dot(w2) # N * D_out
    
    loss = np.square(y_pred - y).sum()
    print(it, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 35510010.23071951
1 34281892.13046157
2 34074734.125160396
3 29411349.856658015
4 20489998.091854304
5 11668584.799194608
6 6023936.860213276
7 3213982.2917437325
8 1931552.1847201223
9 1319138.7238968336
10 990319.1080641226
11 787341.2660798181
12 646729.5316434848
13 541689.5827212998
14 459293.0828214957
15 392657.4292568007
16 338019.13628880715
17 292601.6016398153
18 254454.98076005274
19 222171.49257840414
20 194695.02847144342
21 171171.24794212976
22 150940.07529841454
23 133468.65836097708
24 118348.2631509889
25 105212.12755334821
26 93774.90088814004
27 83782.32976661788
28 75014.9412203486
29 67292.76063474116
30 60470.546511198365
31 54437.26489726166
32 49090.8157124221
33 44338.375711551955
34 40102.61114940273
35 36326.361876069284
36 32950.150611905825
37 29927.813575399858
38 27218.0766254178
39 24780.892509154317
40 22586.72145448323
41 20608.82063594502
42 18822.79870312377
43 17207.230943420498
44 15744.854313734675
45 14419.242103241526
46 13216.699952775927
4

352 0.0001607545155305719
353 0.000152985644330172
354 0.00014559578726564253
355 0.00013856735324912676
356 0.00013188241289701302
357 0.00012552603541866333
358 0.00011947823027178849
359 0.00011372297482511929
360 0.00010824963694246973
361 0.00010304212986673753
362 9.808923115251305e-05
363 9.337695659096457e-05
364 8.889196165642294e-05
365 8.462647531654662e-05
366 8.057310396580029e-05
367 7.671100437336542e-05
368 7.303568131002808e-05
369 6.953759672146827e-05
370 6.62097006301576e-05
371 6.304171905289468e-05
372 6.002763915017351e-05
373 5.7159711839541826e-05
374 5.4429022446472303e-05
375 5.1831053588691196e-05
376 4.935769443196479e-05
377 4.7003762754773144e-05
378 4.476318658300051e-05
379 4.263023784522552e-05
380 4.060039882161286e-05
381 3.866777565041087e-05
382 3.6827934870534405e-05
383 3.507683081666578e-05
384 3.340954801021524e-05
385 3.18224587474245e-05
386 3.0311271216236442e-05
387 2.88722863149981e-05
388 2.750270464200885e-05
389 2.619828264814049e-05
39

In [36]:
x

array([[ 0.9363737 , -0.08733972,  1.82457049, ..., -0.70475688,
         0.59919029,  0.15898148],
       [-0.17386692,  0.11052958,  0.08900119, ..., -2.16529619,
        -0.46091749,  0.51847151],
       [-0.35971548, -0.38077229,  1.30373974, ...,  0.45703854,
         0.16449008, -0.87577523],
       ...,
       [ 0.90966972,  0.46372031,  2.28287688, ...,  0.50346217,
         1.87625441,  1.19782194],
       [-0.62900651, -0.04722447,  0.96398645, ...,  0.52497961,
        -1.59922339,  0.64774964],
       [ 0.59057872,  0.03676984,  0.13818168, ..., -0.73255812,
        -0.25507166, -0.57327667]])

In [37]:
h = x.dot(w1)
h_relu = np.maximum(h, 0) # N * H
y_pred = h_relu.dot(w2) # N * D_out

In [39]:
print(y_pred)

[[-6.19897770e-01 -3.27889017e-03 -6.37807630e-01  3.87374273e-01
   5.12847550e-01 -4.55157062e-02 -1.37827981e+00  2.70522554e-01
  -5.39217484e-01 -2.38794498e-01]
 [ 3.71521615e+00  1.23985845e+00 -1.63640402e+00 -1.16127255e-01
   7.37205732e-01 -1.13148011e+00  6.74760085e-01 -1.05775268e+00
   1.37738167e+00  8.16307661e-01]
 [ 2.21020299e-01 -8.30160260e-01 -1.51661985e-03 -4.68111213e-01
  -1.38337363e-01  1.42199871e+00  1.69774442e-01 -1.37937730e+00
  -5.07513089e-01 -1.19586162e+00]
 [-4.57248575e-01  9.74476277e-01  6.29495699e-01 -5.00896977e-01
   4.86092936e-01  1.14858622e+00 -1.05344784e+00 -1.14153072e-01
  -6.09546575e-01 -2.44806074e-01]
 [ 2.18690978e+00 -1.79978917e+00  1.96658840e+00 -1.69613165e+00
   1.26043620e+00 -8.52327344e-01 -1.00086127e+00 -2.56533542e+00
  -7.52129750e-01  1.68800061e+00]
 [-1.40716281e+00  1.35441566e-01  3.63506492e-01 -5.34181883e-02
   2.79728098e-01  1.00280842e+00  1.66222277e-01  4.98766991e-01
   9.20044489e-01  6.13189324e-01

   2.28831765e-01 -1.37632324e+00]]


In [40]:
print(y)

[[-6.19900773e-01 -3.27193491e-03 -6.37815778e-01  3.87380492e-01
   5.12865050e-01 -4.55173190e-02 -1.37827057e+00  2.70518786e-01
  -5.39211536e-01 -2.38809330e-01]
 [ 3.71521163e+00  1.23986136e+00 -1.63639794e+00 -1.16130863e-01
   7.37202071e-01 -1.13147495e+00  6.74755091e-01 -1.05775081e+00
   1.37738300e+00  8.16307284e-01]
 [ 2.21026344e-01 -8.30168645e-01 -1.49564793e-03 -4.68116919e-01
  -1.38382742e-01  1.42198515e+00  1.69753094e-01 -1.37936792e+00
  -5.07523952e-01 -1.19582321e+00]
 [-4.57247273e-01  9.74478218e-01  6.29484835e-01 -5.00890458e-01
   4.86112177e-01  1.14858155e+00 -1.05343661e+00 -1.14157301e-01
  -6.09546135e-01 -2.44817624e-01]
 [ 2.18690828e+00 -1.79978349e+00  1.96657295e+00 -1.69613003e+00
   1.26046045e+00 -8.52336320e-01 -1.00084689e+00 -2.56534172e+00
  -7.52130774e-01  1.68798749e+00]
 [-1.40716116e+00  1.35439807e-01  3.63508713e-01 -5.34193305e-02
   2.79724895e-01  1.00280627e+00  1.66223313e-01  4.98769233e-01
   9.20044945e-01  6.13192003e-01

   2.28834219e-01 -1.37632777e+00]]


In [41]:
N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
w1 = torch.randn(D_in, H)
w2 = torch.randn(H, D_out)
learning_rate = 1e-6
for it in range(500):
    h = x.mm(w1) # N * H
    h_relu = h.clamp(min=0) # N * H
    y_pred = h_relu.mm(w2) # N * D_out
    
    loss = (y_pred - y).pow(2).sum().item()
    print(it, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h<0] = 0
    grad_w1 = x.t().mm(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 31417710.0
1 26527686.0
2 24937722.0
3 22968808.0
4 19367922.0
5 14410496.0
6 9676195.0
7 6073812.0
8 3788790.0
9 2445303.0
10 1681020.75
11 1232721.25
12 955767.3125
13 772262.875
14 642194.8125
15 544323.1875
16 467407.03125
17 405019.8125
18 353350.3125
19 309921.3125
20 273035.28125
21 241430.546875
22 214163.734375
23 190525.734375
24 169963.53125
25 151985.140625
26 136233.15625
27 122394.3515625
28 110179.625
29 99370.421875
30 89791.7109375
31 81276.1875
32 73690.25
33 66913.078125
34 60845.16796875
35 55403.41796875
36 50520.1953125
37 46121.953125
38 42157.0078125
39 38576.73828125
40 35339.4921875
41 32405.72265625
42 29745.357421875
43 27328.955078125
44 25130.431640625
45 23131.751953125
46 21308.578125
47 19644.166015625
48 18123.12890625
49 16733.29296875
50 15460.185546875
51 14293.107421875
52 13222.2998046875
53 12239.15234375
54 11336.234375
55 10505.71484375
56 9741.6708984375
57 9041.2099609375
58 8394.1845703125
59 7797.2744140625
60 7246.62353515625
61 6738.273

370 0.000549840449821204
371 0.0005318967741914093
372 0.0005155617836862803
373 0.0004985221894457936
374 0.00048315798630937934
375 0.0004677737015299499
376 0.00045365485129877925
377 0.0004400562902446836
378 0.00042597699211910367
379 0.00041318824514746666
380 0.0004004187067039311
381 0.0003890551161020994
382 0.00037835200782865286
383 0.00036671938141807914
384 0.0003555839357431978
385 0.00034549980773590505
386 0.00033552609966136515
387 0.00032594858203083277
388 0.00031594725442118943
389 0.0003074192791245878
390 0.0002985911560244858
391 0.0002903197309933603
392 0.00028226530412212014
393 0.0002750933635979891
394 0.0002672754926607013
395 0.000259857508353889
396 0.00025347521295771003
397 0.0002459472743794322
398 0.00023985806910786778
399 0.00023362608044408262
400 0.00022803385218139738
401 0.00022204613196663558
402 0.0002163606695830822
403 0.00021124276099726558
404 0.00020582473371177912
405 0.0002008841111091897
406 0.00019592337775975466
407 0.000191076571354

In [46]:
N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)
learning_rate = 1e-6
for it in range(500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2) # N * D_out
    
    loss = (y_pred - y).pow(2).sum()
    print(it, loss.item())
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w1.grad.zero_()
        w2.grad.zero_()    

0 33910020.0
1 34408720.0
2 39694176.0
3 42024540.0
4 34819992.0
5 21262160.0
6 10002026.0
7 4434886.0
8 2267234.25
9 1444703.75
10 1077985.25
11 871277.6875
12 729949.625
13 622177.625
14 535730.375
15 464574.625
16 405103.6875
17 354951.8125
18 312320.1875
19 275888.3125
20 244616.734375
21 217623.578125
22 194202.71875
23 173792.546875
24 155934.109375
25 140259.09375
26 126476.53125
27 114314.8046875
28 103557.3828125
29 94003.703125
30 85482.640625
31 77868.5546875
32 71039.5625
33 64904.296875
34 59383.73046875
35 54405.0859375
36 49905.5546875
37 45834.890625
38 42145.1015625
39 38794.2421875
40 35747.875
41 32972.8671875
42 30441.646484375
43 28131.197265625
44 26018.8125
45 24084.3359375
46 22311.62890625
47 20684.61328125
48 19190.298828125
49 17816.16015625
50 16551.59765625
51 15387.384765625
52 14313.8291015625
53 13322.650390625
54 12407.1240234375
55 11560.708984375
56 10777.525390625
57 10052.09375
58 9379.9326171875
59 8756.6416015625
60 8178.4482421875
61 7641.4448242

374 0.000894410302862525
375 0.0008646524511277676
376 0.0008359666098840535
377 0.0008101044222712517
378 0.0007840004400350153
379 0.0007577749202027917
380 0.000734172179363668
381 0.0007112802704796195
382 0.0006894062971696258
383 0.0006685731932520866
384 0.0006477596471086144
385 0.000627306173555553
386 0.0006091886316426098
387 0.0005912478081882
388 0.0005738648469559848
389 0.0005558218108490109
390 0.0005399243091233075
391 0.0005240085883997381
392 0.0005097513785585761
393 0.0004942881059832871
394 0.00048073159996420145
395 0.00046746557927690446
396 0.0004544403054751456
397 0.0004419115139171481
398 0.0004289436328690499
399 0.00041756383143365383
400 0.00040672655450180173
401 0.00039576395647600293
402 0.0003852645168080926
403 0.0003756496880669147
404 0.00036603797343559563
405 0.00035624494194053113
406 0.0003471063100732863
407 0.00033889408223330975
408 0.0003300709358882159
409 0.0003219007339794189
410 0.000313707219902426
411 0.00030543049797415733
412 0.0002

In [52]:
import torch.nn as nn

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = nn.Sequential(
    nn.Linear(D_in, H),
    nn.ReLU(),
    nn.Linear(H, D_out)
)

nn.init.normal_(model[0].weight)
nn.init.normal_(model[2].weight)

loss_fn = nn.MSELoss(reduction='sum')

learning_rate = 1e-6
for it in range(500):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    print(it, loss.item())
    
    model.zero_grad()
    
    loss.backward()
    
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

0 31689638.0
1 32724296.0
2 43239708.0
3 55724848.0
4 55690404.0
5 36149336.0
6 14573041.0
7 4797597.5
8 2072815.375
9 1333131.375
10 1042216.0625
11 867912.9375
12 738389.6875
13 634973.8125
14 550078.5
15 479525.75
16 420273.09375
17 370100.375
18 327376.3125
19 290752.25
20 259194.96875
21 231848.546875
22 208067.28125
23 187275.78125
24 169028.140625
25 152951.3125
26 138737.75
27 126119.8125
28 114890.15625
29 104877.9375
30 95914.7890625
31 87877.15625
32 80643.8515625
33 74119.9921875
34 68223.296875
35 62881.59375
36 58033.26171875
37 53630.71484375
38 49620.31640625
39 45958.0546875
40 42610.19921875
41 39545.34765625
42 36736.1171875
43 34156.3515625
44 31784.3828125
45 29598.5078125
46 27585.337890625
47 25730.6328125
48 24017.23828125
49 22432.86328125
50 20967.447265625
51 19610.1328125
52 18351.296875
53 17182.666015625
54 16097.33203125
55 15088.6865234375
56 14150.8251953125
57 13277.3740234375
58 12463.9794921875
59 11705.3798828125
60 10997.6298828125
61 10336.8105468

378 0.005013212561607361
379 0.00482605118304491
380 0.004642616957426071
381 0.004468442406505346
382 0.004301017615944147
383 0.00414153141900897
384 0.003986474592238665
385 0.0038365228101611137
386 0.0036953953094780445
387 0.0035625773016363382
388 0.0034320733975619078
389 0.003306447993963957
390 0.0031882671173661947
391 0.0030740320216864347
392 0.0029643895104527473
393 0.0028586203698068857
394 0.0027545602060854435
395 0.002658773446455598
396 0.002566480776295066
397 0.0024752365425229073
398 0.0023881648667156696
399 0.0023060194216668606
400 0.0022256188094615936
401 0.002144525060430169
402 0.0020741596817970276
403 0.002003926085308194
404 0.0019363806350156665
405 0.001870522042736411
406 0.0018057612469419837
407 0.0017486147116869688
408 0.0016902480274438858
409 0.0016304469900205731
410 0.0015793677885085344
411 0.0015263736713677645
412 0.0014778129989281297
413 0.0014314731815829873
414 0.0013849986717104912
415 0.0013408889062702656
416 0.0013005660148337483
4

In [51]:
model[0].weight

Parameter containing:
tensor([[-0.0219,  0.0174, -0.0224,  ..., -0.0226,  0.0324, -0.0048],
        [-0.0073, -0.0262,  0.0070,  ...,  0.0038,  0.0042,  0.0199],
        [-0.0261,  0.0089,  0.0087,  ...,  0.0148,  0.0188, -0.0033],
        ...,
        [ 0.0306,  0.0134,  0.0120,  ..., -0.0278,  0.0111,  0.0250],
        [ 0.0182,  0.0191, -0.0268,  ..., -0.0114, -0.0087,  0.0283],
        [ 0.0212, -0.0225, -0.0298,  ..., -0.0150,  0.0003,  0.0022]],
       requires_grad=True)

In [55]:
import torch.nn as nn

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = nn.Sequential(
    nn.Linear(D_in, H),
    nn.ReLU(),
    nn.Linear(H, D_out)
)

# nn.init.normal_(model[0].weight)
# nn.init.normal_(model[2].weight)

loss_fn = nn.MSELoss(reduction='sum')
learning_rate = 1e-4
# optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for it in range(500):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    print(it, loss.item())
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 671.2813110351562
1 620.3229370117188
2 576.82080078125
3 538.9013671875
4 505.6424865722656
5 475.9904479980469
6 449.101806640625
7 424.35845947265625
8 401.5543212890625
9 380.2982482910156
10 360.3229675292969
11 341.62738037109375
12 324.08905029296875
13 307.5159912109375
14 291.855712890625
15 276.9569396972656
16 262.71466064453125
17 249.07386779785156
18 236.08424377441406
19 223.6042022705078
20 211.64398193359375
21 200.21511840820312
22 189.2831268310547
23 178.81756591796875
24 168.83132934570312
25 159.32554626464844
26 150.2563018798828
27 141.62222290039062
28 133.3988494873047
29 125.56388854980469
30 118.1383285522461
31 111.12085723876953
32 104.4796371459961
33 98.2040023803711
34 92.27667999267578
35 86.68698120117188
36 81.40595245361328
37 76.43523406982422
38 71.75569915771484
39 67.34873962402344
40 63.217166900634766
41 59.34611892700195
42 55.70884704589844
43 52.30353546142578
44 49.118282318115234
45 46.1329460144043
46 43.339149475097656
47 40.724353790

346 0.0001430632546544075
347 0.00013798697909805924
348 0.0001330984669039026
349 0.00012838240945711732
350 0.0001238321710843593
351 0.00011944009020226076
352 0.00011520468979142606
353 0.00011113459913758561
354 0.00010719634155975655
355 0.00010340450535295531
356 9.975163266062737e-05
357 9.622413926990703e-05
358 9.281860548071563e-05
359 8.954337681643665e-05
360 8.638796134619042e-05
361 8.333392179338261e-05
362 8.039372914936393e-05
363 7.755709521006793e-05
364 7.482387445634231e-05
365 7.21876131137833e-05
366 6.964385829633102e-05
367 6.719005614286289e-05
368 6.482868775492534e-05
369 6.255147309275344e-05
370 6.034665057086386e-05
371 5.822223101858981e-05
372 5.6179476814577356e-05
373 5.4205254855332896e-05
374 5.230010356171988e-05
375 5.046700971433893e-05
376 4.869269105256535e-05
377 4.698403427028097e-05
378 4.5337521441979334e-05
379 4.3746898882091045e-05
380 4.221422932459973e-05
381 4.073512536706403e-05
382 3.930816819774918e-05
383 3.793191717704758e-05
38

In [56]:
import torch.nn as nn

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

class TwoLayerNet(nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TwoLayerNet, self).__init__()
        self.linear1 = nn.Linear(D_in, H, bias=False)
        self.linear2 = nn.Linear(H, D_out, bias=False)
    
    def forward(self, x):
        y_pred = self.linear2(self.linear1(x).clamp(min=0))
        return y_pred

model = TwoLayerNet(D_in, H, D_out)
loss_fn = nn.MSELoss(reduction='sum')
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for it in range(500):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    print(it, loss.item())
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 736.78076171875
1 718.4276733398438
2 700.47705078125
3 683.061279296875
4 666.0830688476562
5 649.5706176757812
6 633.5545043945312
7 617.9921264648438
8 602.9041748046875
9 588.3569946289062
10 574.1886596679688
11 560.4888305664062
12 547.1692504882812
13 534.2069702148438
14 521.5963745117188
15 509.3280029296875
16 497.3973083496094
17 485.7869873046875
18 474.5148010253906
19 463.5892028808594
20 452.9377746582031
21 442.5401306152344
22 432.4314880371094
23 422.6140441894531
24 413.06036376953125
25 403.7365417480469
26 394.6595458984375
27 385.7978515625
28 377.1307678222656
29 368.74896240234375
30 360.567138671875
31 352.5791015625
32 344.7884521484375
33 337.16436767578125
34 329.6752014160156
35 322.33935546875
36 315.15594482421875
37 308.15582275390625
38 301.2752380371094
39 294.5111083984375
40 287.8530578613281
41 281.32244873046875
42 274.9227600097656
43 268.6654968261719
44 262.56939697265625
45 256.5965576171875
46 250.75064086914062
47 245.02191162109375
48 239.

356 0.00046196350012905896
357 0.00043978786561638117
358 0.00041867452091537416
359 0.00039858988020569086
360 0.00037946453085169196
361 0.0003612528380472213
362 0.00034392662928439677
363 0.0003274302289355546
364 0.00031172618037089705
365 0.0002967818873003125
366 0.0002825545961968601
367 0.00026900932425633073
368 0.0002561055589467287
369 0.0002438308292767033
370 0.00023214447719510645
371 0.0002210186212323606
372 0.00021042634034529328
373 0.00020034032058902085
374 0.00019074301235377789
375 0.00018159954925067723
376 0.00017289540846832097
377 0.00016460182087030262
378 0.00015672070730943233
379 0.00014920967805664986
380 0.00014205080515239388
381 0.00013524141104426235
382 0.00012876583787146956
383 0.00012258758943062276
384 0.00011671219544950873
385 0.00011111549974884838
386 0.00010578789078863338
387 0.0001007113023661077
388 9.588239481672645e-05
389 9.128404053626582e-05
390 8.690178947290406e-05
391 8.272968261735514e-05
392 7.876274321461096e-05
393 7.49779283